import { NextResponse } from "next/server";
import { addUser } from "@/lib/firebase/firestore/user/userUtil";

/*
 * Create new User
 * NOP if User already exists.
 *
 * Params:
 *  None
 * Request body:
 *  first: first name
 *  last: last name,
 *  email_address: email address
 *  user_id: global id of a User
 *  pfp: path to pfp image [optional]
 * Return:
 *  data: id of the new User generated by firestore
 *  error: error or null
 */
export async function POST(req: Request) {
  try {
    // get new user data from req body
    const data = await req.json();
    const { first, last, email_address, user_id, pfp } = data;

    if (!first || !last || !email_address || !user_id) {
      throw new Error("missing required fields");
    }

    const retreived_id = await addUser(first, last, email_address, user_id, pfp);

    return NextResponse.json({ data: { user_id: retreived_id }, error: null });
  } catch (e: unknown) {
    if (e instanceof Error) {
      return NextResponse.json({ data: null, error: e.message});
    } else {
      return NextResponse.json({ data: null, error: "unknown error"});
    }
  }
}
