import { NextResponse } from "next/server";
import { AddUserRequest } from "@/lib/firebase/firestore/types";
import { addUser } from "@/lib/firebase/firestore/user/userUtil";

/*
 * Create new User
 * NOP if User already exists.
 *
 * Params:
 *  None
 * Request body:
 *  first: first name
 *  last: last name,
 *  email_address: email address
 *  user_id: global id of a User
 *  pfp: path to pfp image [optional]
 * Return:
 *  data: id of the new User generated by firestore
 *  error: error or null
 */
export async function POST(req: Request) {
  try {
    // get new user data from req body
    const data: AddUserRequest = await req.json();

    // validate input
    if (!data.first || !data.last || !data.email_address || !data.user_id) {
      throw new Error("missing required fields");
    }

    const id: string = await addUser(data);

    return NextResponse.json({ data: { user_id: id }, error: null });
  } catch (e: unknown) {
    if (e instanceof Error) {
      return NextResponse.json({ data: null, error: e.message});
    } else {
      return NextResponse.json({ data: null, error: "unknown error"});
    }
  }
}
